---
title: Project Review
author: Christian Okitondo
date: "`r file.mtime(knitr::current_input())`"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Wastewater Surveillance for SARS-CoV-2 

Name of project author(s): Leah Laruscy

Name of project reviewer: Christian Okitondo



## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The context of the project is well described in this document. The authors provide a comprehensive background on the COVID-19 pandemic, the causative agent, symptoms, and the impact of the pandemic on society. The authors also provide a detailed summary of previous and related work on wastewater-based detection methods that have been utilized across the globe as an independent and parallel indicator of SARS-CoV-2 viral prevalence. Proper referencing of existing work is also included.

The project is well placed in the context of existing work, and the authors clearly describe why the project was undertaken. The authors aim to conduct a parallel analysis between SARS-CoV-2 wastewater surveillance data and reported COVID-19 clinical case data in Athens-Clarke County, Georgia. The new information they hope to provide is a better understanding of the relationship between wastewater quantifications and reported case data, and to identify the specific wastewater-clinical relationships that are stronger than others. Overall, the context of the project is well-described and provides a clear understanding of the objectives and expected outcomes of the study.

### Summary assessment 
* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments
The research questions are clearly described, and the hypotheses to be addressed are stated. The project aims to address the relationship between SARS-CoV-2 wastewater surveillance data and reported COVID-19 clinical case data in Athens-Clarke County, Georgia.  

### Summary assessment
Question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The data description is clear and the source is provided. The codebook is available in the readme.md file placed in the raw_data folder. 

### Summary assessment

Source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments
The data cleaning/processing and exploration steps are well-explained and reasonable. The alternative methods are not discussed, but the author does discuss the limitations of the data and the possible sources of bias. The exploratory results are shown and meaningful. The paper provides a clear introduction, including background information about COVID-19, the rationale for the study, and the hypotheses to be tested. In the methods section, the author provides a detailed description of the data sources and acquisition process, as well as the statistical analyses used to test the hypotheses. Overall, the manuscript appears to be well-written and thoroughly researched.

### Summary assessment
Essentially no weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

The analysis part is well-explained and presented in a good layout. Made good use of the machine learning lessons we learned.

### Summary assessment

* strong and reasonable analysis


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments
The plots and tables for EDA are really nice. However, only the results from the correlation analysis was reported. Did not see results from the linear regression or any statistical tests mentioned in the methods section


### Summary assessment
* results are presented ok, with room for improvement



## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments
Discussion/Conclusion sections were not available.

### Summary assessment
* minor parts wrong, missing or unclear


## Further comments
Project heading in the right direction. With the results and discussion sections completed, it will make a strong one.



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments
The project is well structured and labelled with appropriate names. There is no irrelevant or redundant file. It was fairly easy to reproduce everything by following the instructions. 


### Summary assessment
* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

Each step of the whole analysis is well-explained. There are plenty of comments justifying and stating the purpose of each line of code.

### Summary assessment

* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

All results are fully reproducible and the readme.me file under each folder provides clear guidance. 

### Summary assessment
* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Overall, the project is well writtend and properly analyzed. Once completed, it will make a good one.

### Summary assessment
* decent level of thoroughness







